// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi5ucIZVWT_7xwU847c9xWIn1MBh_EVK0',
    appId: '1:620582975733:web:0b887cbcbd9b3257caadbc',
    messagingSenderId: '620582975733',
    projectId: 'dhaav-app',
    authDomain: 'dhaav-app.firebaseapp.com',
    storageBucket: 'dhaav-app.firebasestorage.app',
    measurementId: 'G-BHBEM5R2R6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDthiU5_J-MSz1ovNjzz8GLWsCk8vrSJLc',
    appId: '1:620582975733:android:d705f3e0cf465509caadbc',
    messagingSenderId: '620582975733',
    projectId: 'dhaav-app',
    storageBucket: 'dhaav-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnD2xtxBW9AtL_8HMD9bAuw6Ix0aj2ymk',
    appId: '1:620582975733:ios:c066333f335bbdf9caadbc',
    messagingSenderId: '620582975733',
    projectId: 'dhaav-app',
    storageBucket: 'dhaav-app.firebasestorage.app',
    androidClientId: '620582975733-te454ila06bkuf9pofc6keer2coosfsj.apps.googleusercontent.com',
    iosClientId: '620582975733-mn53vakhpqicgtodvakcljlb2p5o6h6b.apps.googleusercontent.com',
    iosBundleId: 'com.dhaav.dhaav',
  );
}
